import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import Random from '../components/Random'
import Theme from '../components/Theme';
import styles from '../styles/Home.module.css'

export default function Home() {

  // const [theme, setTheme] = useState("dark");
  const [activeTheme, setActiveTheme] = useState('dark');
  const inactiveTheme = activeTheme === 'dark' ? 'light' : 'dark' 

  useEffect(() => {
    document.body.dataset.theme = activeTheme;
  }, []);

  useEffect(() => {
    const savedTheme = JSON.parse(localStorage.getItem('saved-theme'))
  if (savedTheme) {
    setActiveTheme(savedTheme)
    }
  }, [])
  
  useEffect(() => {
    localStorage.setItem(
      'saved-theme',
      JSON.stringify(activeTheme)
    )
  }, [activeTheme])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        {/* <script src="http://unpkg.com/swipejs/dist/swipe.min.js"/> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Theme/>
       <Random/>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
