import Head from "next/head"
import Link from "next/link"
import Random from "../components/Random"
import styles from '../styles/Home.module.css'

const App = () => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Lightread</title>
            {/* <script src="http://unpkg.com/swipejs/dist/swipe.min.js"/> */}
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="apple-touch-icon" sizes="128x128" href="favicon.png" />
            <link rel="icon" sizes="192x192" href="favicon.png" />
          </Head>
          <main className={styles.main}>
            {/* {visible && <Base/>} */}
            <Random/>
            {/* {visible && <Base/>}
            {!visible && <Random/>} */}
            </main>
          {/* </body> */}
    
          <footer className={styles.footer}>
            <p><span><Link href='/'>Lightread</Link></span> by <a href="https://www.robinn.io/"
            target="_blank"
            rel="noopener noreferrer"
            >Robin Naghshbandi <span className={styles.pass}>🔖</span></a></p>
            <br/>
            <a className={styles.source} href="https://github.com/robbandi/lightread"
            target="_blank"
            rel="noopener noreferrer"
            >View source on GitHub</a>
          </footer> 
        </div>
      )
    }

export default App